name: CheckForSquadServerUpdate
on:
  workflow_dispatch:
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Setup steamcmd
      uses: CyberAndrii/setup-steamcmd@v1
    - name: Setup python
      uses: actions/setup-python@v2
    - name: Pull repository
      uses: actions/checkout@v2
      with: 
        token: ${{ github.token }}
    - name: Check for updates
      run: python -m pip install -U steam[client] && python ./.github/CheckForSquadServerUpdate.py
    - name: Dispatch UpdateMapRotation workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: UpdateMapRotation
        token: ${{ secrets.PERSONAL_TOKEN }}
    - name: Commit & Push updated file
      uses: EndBug/add-and-commit@v7
      with:
        author_name: DSG-SquadServer Update-Bot
        author_email: privat@skyraptor.eu
        message: 'Updated lastCreated depot cache'

