name: CheckForSquadServerUpdate
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Setup steamcmd
      uses: CyberAndrii/setup-steamcmd@v1
    - name: Setup python
      uses: actions/setup-python@v2
    - name: Pull repository
      uses: actions/checkout@v2
      with: 
        token: ${{ github.token }}
    - name: Check for updates
      id: updatecheck
      continue-on-error: true
      run: python -m pip --disable-pip-version-check install -Uq steam[client] && python ./.github/CheckForSquadServerUpdate.py
    - name: Dispatch UpdateMapRotation workflow
      if: steps.updatecheck.outputs == 'Update found.'
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: UpdateMapRotation
        token: ${{ secrets.PERSONAL_TOKEN }}
    - name: Commit & Push updated file
      if: steps.updatecheck.outputs == 'Update found.'
      uses: EndBug/add-and-commit@v7
      with:
        author_name: DSG-SquadServer Update-Bot
        author_email: privat@skyraptor.eu
        message: 'Updated lastCreated depot cache'

