name: UpdateMapRotation
on:
  workflow_dispatch:
jobs:
  unit-tests:
    runs-on: [self-hosted, ec2, squad]
    steps:
    - name: Pull repository
      uses: actions/checkout@v2
      with: 
        token: ${{ github.token }}
    - name: Stop & Remove any previous Server
      run: docker stop squad-server || true  && docker rm squad-server || true
    - name: Create the squad-server container and install the server
      run: docker run -d --net=bridge -e PORT=7787 -e QUERYPORT=27165 -e RCONPORT=21114 --name=squad-server cm2network/squad
    - name: Wait for Squad Server to install & boot
      run: chmod +x .github/waitForServerStartup.sh && ./.github/waitForServerStartup.sh
    - name: Extract the default LayerRotation, clean and write the result to file
      run: >
        LayerRotation=$(docker exec squad-server cat /home/steam/squad-dedicated/SquadGame/ServerConfig/LayerRotation.cfg) &&
        chmod +x .github/cleanMapRotation.sh && ./.github/cleanMapRotation.sh "$LayerRotation" > ./data/LayerRotation.cfg
    - name: Commit & Push updated file
      uses: EndBug/add-and-commit@v7
      with:
        author_name: DSG-MapRotation Update-Bot
        author_email: privat@skyraptor.eu
        message: 'Updated default LayerRotation'
