name: UpdateSquadServerData
on:
  workflow_dispatch:
jobs:
  unit-tests:
    runs-on: [self-hosted, linux, x64, ec2]
    steps:
    - name: Pull repository
      uses: actions/checkout@v3
      with: 
        token: ${{ github.token }}
        
    - name: Setup python
      uses: actions/setup-python@v4
      
    - name: Install SteamPython
      run: python -m pip --disable-pip-version-check install -Uq steam[client]
    
    - name: Check lock file exists
      id: check_lock
      uses: andstor/file-existence-action@v1
      with:
        files: "tmp/UpdateSquadServerData"
          
    - name: cancelling
      uses: andymckay/cancel-action@0.2
      if: steps.check_lock.outputs.files_exists == 'true'
        
    - name: Write the UpdateSquadServerData lock file
      run: touch tmp/UpdateSquadServerData
      
    - name: Commit lock file
      uses: EndBug/add-and-commit@v9
      with:
        author_name: DSG-MapRotation Update-Bot
        author_email: privat@skyraptor.eu
        message: 'Created UpdateMapRotation lock file'
        add: tmp/UpdateSquadServerData
  
    - name: Update depot cache
      run: python3 ./.github/CheckForSquadServerUpdate.py
        
    - name: Stop & Remove any previous Server
      run: docker stop squad-server || true  && docker rm squad-server || true
      
    - name: Create the squad-server container and install the server
      run: docker run -d --net=bridge -e PORT=7787 -e QUERYPORT=27165 -e RCONPORT=21114 --name=squad-server cm2network/squad
      
    - name: Wait for Squad Server to install & boot
      run: chmod +x .github/waitForServerStartup.sh && ./.github/waitForServerStartup.sh

    - name: Extract raw ServerConfig folder (and convert CRLF to LF)
      run: |
        mkdir -p data/ServerConfig
        docker cp squad-server:/home/steam/squad-dedicated/SquadGame/ServerConfig/. data/ServerConfig
        find ./data/ServerConfig/ -type f -print0 | xargs -0 dos2unix

    - name: Extract the default LayerRotation, clean and write the result to file
      run: >
        LayerRotation=$(docker exec squad-server cat /home/steam/squad-dedicated/SquadGame/ServerConfig/LayerRotation.cfg) &&
        chmod +x .github/cleanMapRotation.sh && ./.github/cleanMapRotation.sh "$LayerRotation" > ./data/LayerRotation.cfg
        
    - name: Extract the LoadedLayersList by analyzing what layers the server did actually load.
      run: docker exec squad-server sed -n "s/^.*LogSquad:\sAdded\sAvailable\sLayer\s:\s\(\S*\).*$/\1/p" /home/steam/squad-dedicated/SquadGame/Saved/Logs/SquadGame.log > ./data/LoadedLayersList.cfg
        
    - name: Extract the InvalidLayersList by analyzing what layers could not be added by the server.
      run: |
        docker exec squad-server sed -n "s/^.*LogSquad:\sWarning:\s\(\S*\)\swas\snot\sadded\sto\srotation\slist,\splease\scheck\sthat\sit\sis\sa\svalid\slayer.*$/\1/p" /home/steam/squad-dedicated/SquadGame/Saved/Logs/SquadGame.log > /tmp/InvalidLayersList.cfg
        grep -F -x -v -q -f ./data/ServerConfig/ExcludedLayers.cfg /tmp/InvalidLayersList.cfg > ./data/InvalidLayersList.cfg
        
    - name: Remove the UpdateSquadServerData lock file
      if: always()
      run: rm tmp/UpdateSquadServerData
        
    - name: Commit & Push updated file
      if: always()
      uses: EndBug/add-and-commit@v9
      with:
        author_name: DSG-MapRotation Update-Bot
        author_email: privat@skyraptor.eu
        message: 'Updated Squad-Server Data!'
